# Generated by Django 3.0.7 on 2020-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialist_signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('speciality', models.CharField(max_length=256)),
                ('experience', models.IntegerField()),
                ('place_of_practice', models.TextField(max_length=1000)),
                ('postal_code', models.IntegerField()),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
