# Generated by Django 3.0.7 on 2020-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_specialist_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_signup',
            name='speciality',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
