# Generated by Django 3.0.7 on 2020-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_auto_20200629_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_signup',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialist_signup',
            name='place_of_practice',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='specialist_signup',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
