# Generated by Django 3.0.7 on 2020-07-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_name',
            new_name='specialist_name',
        ),
    ]
