# Generated by Django 3.0.7 on 2020-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0008_appointment_type_of_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(max_length=256, null=True)),
                ('email_receiver', models.EmailField(max_length=256, null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
