# Generated by Django 2.0 on 2020-07-03 19:34

import backendapi.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0009_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=256)),
                ('content', models.TextField(validators=[backendapi.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
