# Generated by Django 2.0 on 2020-07-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0011_message_listener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
