# Generated by Django 2.0 on 2020-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0012_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='app/img')),
                ('title', models.CharField(max_length=256, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('title', 'email')},
        ),
    ]
